version: "3.8"

services:
  postgres:
    image: postgres:15  
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5432"  
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5433", "-d", "learni_db"]
      interval: 60s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 10s
      retries: 5

  celery_worker:
    build: .
    restart: always
    container_name: celery_worker_container
    command: bash -c "celery -A tasks.celery_app worker --loglevel=info"
    depends_on:
      - redis
      - postgres

  flower:
    image: mher/flower
    container_name: flower_container
    command: bash -c "flower --broker=redis://redis:6379/0"
    ports:
      - "5555:5555"
    depends_on:
      - redis

  learni_app:
    build: .
    container_name: learni_app_container
    command: bash -c "alembic upgrade head && python main.py"
    depends_on:
      - redis
      - postgres
      - celery_worker

volumes:
  postgres_data:
