version: "3.8"

services:
  postgres:
    image: postgres:15  
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5432"  
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "alex"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
