version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '%(levelname)-8s %(name)s:%(funcName)s — %(message)s'

  development_format:
    format: '[%(levelname)s] %(filename)s:%(funcName)s:%(lineno)d — %(message)s'

  production_format:
    format: '[%(asctime)s.%(msecs)03d] %(module)s:%(lineno)d %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

filters:
  development_filter:
    (): core.log_filters.DevelopmentFilter

handlers:
  default:
    (): logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  development_stdout_handler:
    (): logging.StreamHandler
    formatter: development_format
    filters: [ development_filter ]
    stream: ext://sys.stdout

  production_stderr_handler:
    (): logging.StreamHandler
    formatter: production_format

loggers:
  development:
    level: DEBUG
    handlers: [ development_stdout_handler ]
    propagate: False

  production:
    level: WARNING
    handlers: [ production_stderr_handler ]
    propagate: False

root:
  formatter: default
  handlers: [ default ]
