"""fixed models relationships

Revision ID: 5a7df8a0b9f7
Revises: c6e1907b996b
Create Date: 2024-12-24 12:54:23.296609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a7df8a0b9f7"
down_revision: Union[str, None] = "c6e1907b996b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
