"""updated metadata in Base model

Revision ID: c6e1907b996b
Revises: ca80473a5f39
Create Date: 2024-12-24 10:53:36.895977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6e1907b996b"
down_revision: Union[str, None] = "ca80473a5f39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("my_words_word_key", "my_words", type_="unique")
    op.create_unique_constraint(op.f("uq_my_words_word"), "my_words", ["word"])
    op.drop_constraint("topics_name_topic_key", "topics", type_="unique")
    op.create_unique_constraint(
        op.f("uq_topics_name_topic"), "topics", ["name_topic"]
    )
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.drop_constraint("words_word_key", "words", type_="unique")
    op.create_unique_constraint(op.f("uq_words_word"), "words", ["word"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_words_word"), "words", type_="unique")
    op.create_unique_constraint("words_word_key", "words", ["word"])
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_constraint(op.f("uq_topics_name_topic"), "topics", type_="unique")
    op.create_unique_constraint(
        "topics_name_topic_key", "topics", ["name_topic"]
    )
    op.drop_constraint(op.f("uq_my_words_word"), "my_words", type_="unique")
    op.create_unique_constraint("my_words_word_key", "my_words", ["word"])
    # ### end Alembic commands ###
