"""create words table

Revision ID: 73d8fb95be32
Revises: 0e06995c41c8
Create Date: 2024-12-17 18:18:18.193880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73d8fb95be32"
down_revision: Union[str, None] = "0e06995c41c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=50), nullable=False),
        sa.Column("translation", sa.String(length=100), nullable=False),
        sa.Column("example_sent", sa.Text(), nullable=False),
        sa.Column(
            "word_level",
            sa.Enum(
                "BEGINNER", "INTERMEDIATE", "ADVANCED", name="levelwordenum"
            ),
            nullable=False,
        ),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("words")
    # ### end Alembic commands ###
