"""create user_words table

Revision ID: ca80473a5f39
Revises: 1f55574b7627
Create Date: 2024-12-17 19:58:37.964381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca80473a5f39"
down_revision: Union[str, None] = "1f55574b7627"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learn_config_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learn_config_id"],
            ["learning_config.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id", "topic_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_topic")
    # ### end Alembic commands ###
