"""Fix one-to-one relationship between Word and EngWord

Revision ID: 015eb3bfb52e
Revises: 66c51308620a
Create Date: 2025-01-04 18:35:24.333048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "015eb3bfb52e"
down_revision: Union[str, None] = "66c51308620a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
