"""created model eng words

Revision ID: 66c51308620a
Revises: b073292e26cf
Create Date: 2025-01-03 17:37:20.421858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66c51308620a"
down_revision: Union[str, None] = "b073292e26cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eng_words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=75), nullable=False),
        sa.Column(
            "word_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", name="levelwordenum"),
            nullable=False,
        ),
        sa.Column("part_speech", sa.String(length=50), nullable=False),
        sa.Column("file_us_link", sa.String(length=255), nullable=False),
        sa.Column("file_uk_link", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eng_words")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eng_words")
    # ### end Alembic commands ###
