"""new filed for Word model

Revision ID: f309499e09f6
Revises: 5a7df8a0b9f7
Create Date: 2025-01-03 13:45:23.472677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f309499e09f6"
down_revision: Union[str, None] = "5a7df8a0b9f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "words",
        sa.Column("file_us_link", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "words",
        sa.Column("file_uk_link", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("words", "file_uk_link")
    op.drop_column("words", "file_us_link")
    # ### end Alembic commands ###
