"""fixed column eng_word_id

Revision ID: 194c6b4e06b5
Revises: dfad31fc35b3
Create Date: 2025-01-04 19:00:56.084667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "194c6b4e06b5"
down_revision: Union[str, None] = "dfad31fc35b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ru_learn", sa.Column("eng_word_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_ru_learn_eng_word_id_eng_words"),
        "ru_learn",
        "eng_words",
        ["eng_word_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_ru_learn_eng_word_id_eng_words"),
        "ru_learn",
        type_="foreignkey",
    )
    op.drop_column("ru_learn", "eng_word_id")
    # ### end Alembic commands ###
